---
# file: ssh/tasks/configuration.yml
#
# configuration tasks.
#

- name: configuration | ensure ssh_configuration integrity
  template:
    src=etc/ssh/ssh_config.j2
    dest="{{ ssh_config_path }}"
    owner=root
    group=root
    mode=0644
  become: yes
  notify: restart ssh

- name: configuration | ensure user .ssh directory is present
  file:
    path="~{{ item.key }}/.ssh"
    owner="{{ item.key }}"
    group="{{ item.key }}"
    mode=0700
    state=directory
  become: yes
  with_dict: "{{ ssh_config_user }}"

- name: configuration | ensure user ssh configuration integrity
  template:
    src=home/user/ssh/config.j2
    dest="~{{ item.key }}/.ssh/config"
    owner="{{ item.key }}"
    group="{{ item.key }}"
    mode=0600
  become: yes
  with_dict: "{{ ssh_config_user }}"
