---
# file: ssh/tasks/main.yml
#
# tasks file
#

- name: include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "../defaults/{{ ansible_distribution | lower }}.yml"
    - "../defaults/{{ ansible_os_family | lower }}.yml"

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: check if hostnames need to be hashed
  command: grep HashKnownHosts {{ ssh_config }} | awk '{ print $2 }'
  register: task_hash_hostname

- name: register ssh_known_hosts_hash fact
  set_fact:
    ssh_known_hosts_hash: task_hash_hostname.stdout.lower() == 'yes'

- include: configuration.yml
  tags: configuration
