---
# file: ssh/tasks/validation.yml
#
# validation tasks.
#

- name: validation | ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: item is not defined
  with_items:
    - ssh_config
    - ssh_config_path
    - ssh_config_user
    - ssh_known_hosts_global_scan
    - ssh_known_hosts_global_path
    - ssh_known_hosts_user_scan

- name: validation | keys of ssh_known_hosts_user_scan have dictionary with user key
  fail:
    msg="user {{ item }} on ssh_known_hosts_user_scan variable is missing the user key"
  when: item.user is not defined
  with_items: "{{ ssh_known_hosts_user_scan }}"

- name: validation | keys of ssh_known_hosts_user_scan have dictionary with hosts key
  fail:
    msg="user {{ item }} on ssh_known_hosts_user_scan variable is missing the hosts list"
  when: item.hosts is not defined
  with_items: "{{ ssh_known_hosts_user_scan }}"
