---
# file: ssh/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - ssh_config
    - ssh_config_path
    - ssh_known_hosts_global
    - ssh_known_hosts_path
